// Generated by EmDash on dev server start

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Recipe {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  prep_time?: string;
  cook_time?: string;
  servings?: string;
  ingredients?: string;
  allergens?: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  cottage_license_notice?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Product {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  price: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  description?: string;
  net_weight?: string;
  cottage_license_number?: string;
  matched_recipe_slug?: string;
  explicit_ingredients?: string;
  allergens?: string;
  in_stock?: boolean;
  stripe_price_id?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    recipes: Recipe;
    products: Product;
  }
}